### ISSUE TITLE
关于refresh.py中的ACCESS_TOKEN, REFRESH_TOKEN如何获取

### ISSUE THREAD

**Issue by Moore-Tian** [SK-415/BiliSessdata#4]
在源代码中这两个变量的赋值语句是：
```python
ACCESS_TOKEN = os.environ['ACCESS_TOKEN']
REFRESH_TOKEN = os.environ['REFRESH_TOKEN']
```

似乎是需要预先在环境变量中配置好？但是我的环境变量中确实没这两项，运行会报错。

而我四处查找，也查不到怎么这里的两个token应该是什么、功能是什么、又该去哪里获取。希望大佬解答（求求了）。

**Comment by SK-415** [comment]
这两个 TOKEN 请参考 [易姐的文档](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/cookie_refresh.md) 自行获取，这段代码是利用 GitHub Actions 自动更新的，所以这两个环境变量实际上是存在项目设置里面（见下图）。同时这段代码已经年久失修，大概率无法直接运行，需要根据前面的文档进行修改。
![image](https://github.com/SK-415/BiliSessdata/assets/36433929/0a3cd31b-8982-43d9-a403-41dddf2e8263)
